### ISSUE TITLE
Suggestion:  Change your Patreon amounts.

### ISSUE THREAD

**Issue by delebash** [GameDev4K/unreal-open-land#10]
They are to high for a new product.  Try 1$ for  Fan 10$ for backer, maybe 25$ for priority support and priority feature requests. Something like this.  I care much more about support, tutorials, feature requests than I do about having my company logo on this project or in a video. I think, hope you will get more support as I like the idea and look forward to future enhancements.

Thanks,
Dan

**Comment by arunoda** [comment]
@delebash thanks for your kind words.
Anyway, I am going to close my Patreon account for now.
The revenue I generated from the Marketplace is sustainable.

Thanks again.
