### ISSUE TITLE
RVT material issue

### ISSUE THREAD

**Issue by purunzone** [GameDev4K/unreal-open-land#22]
When I opened the sample map, the following error message came out from the manual.How should I modify it?

![image](https://user-images.githubusercontent.com/16097860/113954887-b0c0ce80-9855-11eb-9850-7bbb6d67ee75.png)

**Comment by purunzone** [comment]
I solved the problem.

**Comment by arunoda** [comment]
Cool. I hope you didn't enabled virtual texturing in your project.
